version: '3'

services:
  app:
    restart: unless-stopped
    build: .
    ports:
      - "7777:80"
    volumes:
      - .:/var/www/html
    environment:
      - DATABASE_URL
      - API_TOKEN

  database:
    image: postgres:10
    ports:
      - "54322:5432"
    volumes:
      - db_data:/var/lib/postgresql/data:rw

volumes:
  db_data:
