<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK5v6Uf2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK5v6Uf2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK5v6Uf2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK5v6Uf2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerK5v6Uf2\App_KernelDevDebugContainer([
    'container.build_hash' => 'K5v6Uf2',
    'container.build_id' => 'db81b6e9',
    'container.build_time' => 1649888643,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK5v6Uf2');
